### ISSUE TITLE
서비스 서버 클라이언트 웹 제어 테스트

### ISSUE THREAD

**Issue by kuyeon** [miraecityDev/total_care_project#2]
1. 서비스 서버 노드 개발(노드 명: action server)
2. 서비스 클라이언트 라이브러리 개발
3. 웹 제어 테스트

**Comment by thelineover** [comment]
# 서비스 서버 클라이언트 웹 제어 테스트 #2

## Todo list

### 1. 서비스 서버 노드 개발(노드명: action_server)
- [ ] Do something action 1
```python
print("어떤 동작 기능을 하게 할것임 1")
```
- [ ] Do something action 2
```python
print("어떤 동작 기능을 하게 할것임 2")
```

### 2. 서비스 클라이언트 라이브러리 개발
- [ ] Do something action 1
- [ ] Do something action 2

### 3. 웹 제어 테스트
- [ ] Do something action 1
- [ ] Do something action 2

@kuyeon 저라면 위와 같이 업무를 관리하겠습니다. 생각해보시죠

**Comment by kuyeon** [comment]
넵 피드백 감사합니다. 고려해보겠습니다.
